Refactor project structure
devandcoffee/mobileTournamentApp pull request #5
Opened 2017-07-31 23:42 UTC by danicc

Create index files inside folders grouped by feature in  order to improve paths of imported components.

2017-08-01 12:06 UTC, FacundoGFlores requested changes
Generalmente ya no es buena práctica utilizar el método `.bind` para los métodos de una clase. Es un mejor enfoque utilizar arrow functions de es6 para evitar lo anterior.

2017-08-01 12:06 UTC, FacundoGFlores commented on src/components/shared/LeftMenu.js
> +                onPress={() => this.props.navigation.navigate(data)}
Sería mejor utilizar destructuring para navigation.

2017-08-01 12:06 UTC, FacundoGFlores commented on src/components/shared/LeftMenu.js
> +                uri: 'https://github.com/GeekyAnts/NativeBase-KitchenSink/raw/react-navigation/img/logo.png'
Los uris sería mejor ponerlas como constantes al principio del archivo, o bien separarlas en un archivo de constantes.

2017-08-01 12:07 UTC, mattgaviota submitted a review, later dismissed

2017-08-02 22:37 UTC, danicc commented on src/components/shared/LeftMenu.js
> +                uri: 'https://github.com/GeekyAnts/NativeBase-KitchenSink/raw/react-navigation/img/logo.png'
Son solo temporales porque deberiamos sacarlas desde el api pero de todas formas voy a ponerlas al principio del archivo.

2017-08-02 23:01 UTC, FacundoGFlores requested changes

2017-08-02 23:01 UTC, FacundoGFlores commented on src/components/shared/LeftMenu.js
> +const logoImage = 'https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/img/logo.png';
es buena práctica poner las constantes con uppercase

2017-08-05 18:23 UTC, FacundoGFlores approved these changes

2017-08-05 22:41 UTC, merged